// Tutorial lesson definitions
// board: 8x8 array, null = empty, uppercase = white, lowercase = black
// expectedMoves: array of [fromR, fromC, toR, toC] — any one of these is a valid "correct" move
// highlightSquares: squares to pulse to guide the player (optional)

export const LESSONS = [
  // ─── Chapter 1: The Board & Setup ───────────────────────────────────────────
  {
    id: 'board-intro',
    chapter: 'The Board',
    title: 'Welcome to Chess',
    icon: '♟',
    description: 'Chess is played on an 8×8 board of alternating light and dark squares. White always moves first. Your goal is to trap (checkmate) the enemy King.',
    board: null, // no interactive board, just text
    interactive: false,
  },
  {
    id: 'board-setup',
    chapter: 'The Board',
    title: 'Starting Position',
    icon: '♙',
    description: 'This is how the pieces start. White occupies rows 1–2, Black rows 7–8. Notice each side mirrors the other. Take a moment to study the layout.',
    board: [
      ['r','n','b','q','k','b','n','r'],
      ['p','p','p','p','p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P','P','P','P','P','P','P'],
      ['R','N','B','Q','K','B','N','R'],
    ],
    interactive: false,
  },

  // ─── Chapter 2: The Pawns ────────────────────────────────────────────────────
  {
    id: 'pawn-move',
    chapter: 'The Pawn',
    title: 'How Pawns Move',
    icon: '♙',
    description: 'Pawns move forward one square at a time — but on their very first move they can advance two squares. Move the pawn forward to continue.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[6,4,5,4],[6,4,4,4]],
    hint: 'Click the pawn on e2, then click e3 or e4 to move it forward.',
  },
  {
    id: 'pawn-capture',
    chapter: 'The Pawn',
    title: 'Pawns Capture Diagonally',
    icon: '♙',
    description: 'Pawns capture one square diagonally forward — they cannot capture straight ahead. Capture the black pawn!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'p',null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[5,4,4,3]],
    hint: 'Click your pawn on e3, then click the black pawn on d4 to capture it diagonally.',
  },

  // ─── Chapter 3: The Rook ─────────────────────────────────────────────────────
  {
    id: 'rook-move',
    chapter: 'The Rook',
    title: 'How the Rook Moves',
    icon: '♖',
    description: 'The Rook slides any number of squares horizontally or vertically. It cannot jump over other pieces. Move the rook anywhere to continue.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'R',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null, // any rook move is valid
    movingPiece: 'R',
    hint: 'Click the Rook, then click any square in the same row or column.',
  },

  // ─── Chapter 4: The Bishop ───────────────────────────────────────────────────
  {
    id: 'bishop-move',
    chapter: 'The Bishop',
    title: 'How the Bishop Moves',
    icon: '♗',
    description: 'The Bishop slides any number of squares diagonally. Each bishop stays on its own color for the entire game. Move the bishop to continue.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'B',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'B',
    hint: 'Click the Bishop, then click any square diagonally from it.',
  },

  // ─── Chapter 5: The Knight ───────────────────────────────────────────────────
  {
    id: 'knight-move',
    chapter: 'The Knight',
    title: 'How the Knight Moves',
    icon: '♘',
    description: 'The Knight moves in an "L" shape: two squares in one direction, then one square perpendicular. It\'s the only piece that can jump over others!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'N',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'N',
    hint: 'Click the Knight, then click one of the highlighted L-shaped squares.',
  },

  // ─── Chapter 6: The Queen ────────────────────────────────────────────────────
  {
    id: 'queen-move',
    chapter: 'The Queen',
    title: 'How the Queen Moves',
    icon: '♕',
    description: 'The Queen is the most powerful piece — she can move any number of squares in any direction (horizontal, vertical, or diagonal). Use her wisely!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'Q',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'Q',
    hint: 'Click the Queen, then click any square she can reach.',
  },

  // ─── Chapter 7: The King ─────────────────────────────────────────────────────
  {
    id: 'king-move',
    chapter: 'The King',
    title: 'How the King Moves',
    icon: '♔',
    description: 'The King can move one square in any direction. Protect your King at all costs — if he is trapped with no escape (checkmate), you lose!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'K',
    hint: 'Click the King, then click any adjacent square to move him.',
  },

  // ─── Chapter 8: Check & Checkmate ────────────────────────────────────────────
  {
    id: 'check',
    chapter: 'Check & Checkmate',
    title: 'Putting the King in Check',
    icon: '⚔️',
    description: 'When your piece directly threatens the enemy King, that\'s "Check!" The opponent must immediately deal with the threat. Give check by moving the Queen!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'Q',null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[6,3,0,3],[6,3,1,3],[6,3,2,3],[6,3,3,3],[6,3,4,3],[6,3,5,3]],
    hint: 'Move the Queen up the d-file to give check to the black King.',
  },
  {
    id: 'checkmate',
    chapter: 'Check & Checkmate',
    title: 'Checkmate in One!',
    icon: '♛',
    description: 'Checkmate ends the game immediately. The black King has nowhere to go. Move the Queen to deliver checkmate!',
    board: [
      ['k',null,null,null,null,null,null,null],
      ['p','p',null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'Q',null,null,'K',null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,3,1,3]],
    hint: 'Bring the Queen to d7 — that\'s checkmate!',
  },
];

export const CHAPTERS = [...new Set(LESSONS.map(l => l.chapter))];