// Tutorial lesson definitions
// board: 8x8 array, null = empty, uppercase = white, lowercase = black
// expectedMoves: array of [fromR, fromC, toR, toC] — any one of these is a valid "correct" move
// highlightSquares: squares to pulse to guide the player (optional)

export const LESSONS = [
  // ─── Chapter 1: The Board & Setup ───────────────────────────────────────────
  {
    id: 'board-intro',
    chapter: 'The Board',
    title: 'Welcome to Chess',
    icon: '♟',
    description: 'Chess is played on an 8×8 board of alternating light and dark squares. White always moves first. Your goal is to trap (checkmate) the enemy King.',
    board: null, // no interactive board, just text
    interactive: false,
  },
  {
    id: 'board-setup',
    chapter: 'The Board',
    title: 'Starting Position',
    icon: '♙',
    description: 'This is how the pieces start. White occupies rows 1–2, Black rows 7–8. Notice each side mirrors the other. Take a moment to study the layout.',
    board: [
      ['r','n','b','q','k','b','n','r'],
      ['p','p','p','p','p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P','P','P','P','P','P','P'],
      ['R','N','B','Q','K','B','N','R'],
    ],
    interactive: false,
  },

  // ─── Chapter 2: The Pawns ────────────────────────────────────────────────────
  {
    id: 'pawn-move',
    chapter: 'The Pawn',
    title: 'How Pawns Move',
    icon: '♙',
    description: 'Pawns move forward one square at a time — but on their very first move they can advance two squares. Move the pawn forward to continue.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[6,4,5,4],[6,4,4,4]],
    hint: 'Click the pawn on e2, then click e3 or e4 to move it forward.',
  },
  {
    id: 'pawn-capture',
    chapter: 'The Pawn',
    title: 'Pawns Capture Diagonally',
    icon: '♙',
    description: 'Pawns capture one square diagonally forward — they cannot capture straight ahead. Capture the black pawn!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'p',null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[5,4,4,3]],
    hint: 'Click your pawn on e3, then click the black pawn on d4 to capture it diagonally.',
  },

  // ─── Chapter 3: The Rook ─────────────────────────────────────────────────────
  {
    id: 'rook-move',
    chapter: 'The Rook',
    title: 'How the Rook Moves',
    icon: '♖',
    description: 'The Rook slides any number of squares horizontally or vertically. It cannot jump over other pieces. Move the rook anywhere to continue.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'R',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null, // any rook move is valid
    movingPiece: 'R',
    hint: 'Click the Rook, then click any square in the same row or column.',
  },

  // ─── Chapter 4: The Bishop ───────────────────────────────────────────────────
  {
    id: 'bishop-move',
    chapter: 'The Bishop',
    title: 'How the Bishop Moves',
    icon: '♗',
    description: 'The Bishop slides any number of squares diagonally. Each bishop stays on its own color for the entire game. Move the bishop to continue.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'B',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'B',
    hint: 'Click the Bishop, then click any square diagonally from it.',
  },

  // ─── Chapter 5: The Knight ───────────────────────────────────────────────────
  {
    id: 'knight-move',
    chapter: 'The Knight',
    title: 'How the Knight Moves',
    icon: '♘',
    description: 'The Knight moves in an "L" shape: two squares in one direction, then one square perpendicular. It\'s the only piece that can jump over others!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'N',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'N',
    hint: 'Click the Knight, then click one of the highlighted L-shaped squares.',
  },

  // ─── Chapter 6: The Queen ────────────────────────────────────────────────────
  {
    id: 'queen-move',
    chapter: 'The Queen',
    title: 'How the Queen Moves',
    icon: '♕',
    description: 'The Queen is the most powerful piece — she can move any number of squares in any direction (horizontal, vertical, or diagonal). Use her wisely!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'Q',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'Q',
    hint: 'Click the Queen, then click any square she can reach.',
  },

  // ─── Chapter 7: The King ─────────────────────────────────────────────────────
  {
    id: 'king-move',
    chapter: 'The King',
    title: 'How the King Moves',
    icon: '♔',
    description: 'The King can move one square in any direction. Protect your King at all costs — if he is trapped with no escape (checkmate), you lose!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'K',
    hint: 'Click the King, then click any adjacent square to move him.',
  },

  // ─── Chapter: Special Moves ──────────────────────────────────────────────────
  {
    id: 'castling-kingside',
    chapter: 'Special Moves',
    title: 'Castling: Kingside',
    icon: '🏰',
    description: 'Castling is a special move that protects your King and activates your Rook in one move. Move the King two squares toward the Rook — the Rook jumps over to the other side. You can only castle if neither piece has moved, the path is clear, and the King isn\'t passing through an attacked square. Castle kingside!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,'R'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,4,7,6]],
    hint: 'Click your King on e1, then click g1. The King moves two squares right, and the Rook jumps over to f1.',
  },
  {
    id: 'castling-queenside',
    chapter: 'Special Moves',
    title: 'Castling: Queenside',
    icon: '🏰',
    description: 'Queenside castling works the same way — the King moves two squares toward the Rook on the left, and the Rook jumps over. Note that the b1 square must also be empty, even though the King doesn\'t pass through it. Castle queenside!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['R',null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,4,7,2]],
    hint: 'Click your King on e1, then click c1. The King moves two squares left, and the Rook jumps over to d1.',
  },
  {
    id: 'en-passant',
    chapter: 'Special Moves',
    title: 'En Passant',
    icon: '👻',
    description: 'En passant ("in passing") is a special pawn capture. When an enemy pawn moves two squares forward and lands beside yours, you may capture it as if it only moved one square — but only on your very next move! The black pawn just advanced two squares. Capture it en passant!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'p','P',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    enPassantTarget: [2, 3],
    expectedMoves: [[3,4,2,3]],
    hint: 'Click your pawn on e5, then click d6 (the empty square behind the black pawn). Your pawn captures diagonally to d6 — the black pawn on d5 is removed even though you moved to an empty square!',
  },
  {
    id: 'pawn-promotion',
    chapter: 'Special Moves',
    title: 'Pawn Promotion',
    icon: '👑',
    description: 'When a pawn reaches the far end of the board, it must promote — it transforms into a Queen, Rook, Bishop, or Knight of your choice. Almost always, you\'ll pick the Queen since she\'s the most powerful piece. Push your pawn to the last rank to promote it!',
    board: [
      [null,null,null,null,'k',null,null,null],
      ['P',null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[1,0,0,0]],
    hint: 'Click your pawn on a7, then click a8. The pawn promotes to a Queen — a powerful new piece joins the battle!',
  },

  // ─── Chapter 8: Check & Checkmate ────────────────────────────────────────────
  {
    id: 'check',
    chapter: 'Check & Checkmate',
    title: 'Putting the King in Check',
    icon: '⚔️',
    description: 'When your piece directly threatens the enemy King, that\'s "Check!" The opponent must immediately deal with the threat. Give check by moving the Queen!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'Q',null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[6,3,0,3],[6,3,1,3],[6,3,2,3],[6,3,3,3],[6,3,4,3],[6,3,5,3]],
    hint: 'Move the Queen up the d-file to give check to the black King.',
  },
  {
    id: 'checkmate',
    chapter: 'Check & Checkmate',
    title: 'Checkmate in One!',
    icon: '♛',
    description: 'Checkmate ends the game immediately. The black King is trapped in the corner — his own pawns block his escape. Slide the Queen to c8 to deliver checkmate!',
    board: [
      ['k',null,null,null,null,null,null,null],
      ['p','p',null,null,null,null,null,null],
      [null,null,'Q',null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[2,2,0,2]],
    hint: 'Move the Queen from c6 up to c8. The King on a8 is in check, b8 is covered by the Queen, and the pawns on a7 and b7 block any escape — checkmate!',
  },

  // ─── Chapter: Stalemate & Draws ──────────────────────────────────────────────
  {
    id: 'stalemate',
    chapter: 'Stalemate & Draws',
    title: 'Stalemate',
    icon: '🤝',
    description: 'Stalemate is a draw that happens when the player whose turn it is has NO legal moves — but their King is NOT in check. It\'s not checkmate because the King isn\'t attacked. In this position, it\'s Black\'s turn. The Black King on h8 has no safe squares: g8 and g7 are covered by the white Queen, and h7 is covered diagonally. Since the King isn\'t in check, this is stalemate — a draw, not a win!',
    board: [
      [null,null,null,null,null,null,null,'k'],
      [null,null,null,null,null,'K',null,null],
      [null,null,null,null,null,null,'Q',null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
    ],
    interactive: false,
  },
  {
    id: 'threefold-repetition',
    chapter: 'Stalemate & Draws',
    title: 'Threefold Repetition',
    icon: '🔁',
    description: 'If the exact same position occurs three times in a game (with the same player to move and the same castling/en passant rights), either player can claim a draw. This prevents endless shuffling of pieces back and forth. It\'s a safety valve — if nobody is making progress, the game ends in a draw. You\'ll see this often when players repeat moves to avoid risk or secure a result.',
    board: null,
    interactive: false,
  },
  {
    id: 'insufficient-material',
    chapter: 'Stalemate & Draws',
    title: 'Insufficient Material',
    icon: '⚖️',
    description: 'A draw is automatic when neither side has enough pieces to deliver checkmate. King vs King can never produce checkmate — neither King can attack the other. King + Bishop vs King and King + Knight vs King are also draws, since a single minor piece can\'t force checkmate. In this position, only the two Kings remain — the game is a draw by insufficient material.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: false,
  },
];

export const CHAPTERS = [...new Set(LESSONS.map(l => l.chapter))];