// Advanced concepts lessons: zugzwang, prophylaxis, two weaknesses,
// rook on the 7th, minority attack, positional sacrifice.

export const ADVANCED_LESSONS = [
  {
    id: 'advanced-intro',
    chapter: 'Advanced Concepts',
    title: 'Thinking Beyond the Board',
    icon: '🧩',
    description: 'You\'ve mastered the fundamentals — now it\'s time for the ideas that separate club players from tournament winners. In this chapter you\'ll learn zugzwang (when having the move is a curse), prophylaxis (stopping opponent plans before they start), the principle of two weaknesses (creating problems on both sides of the board), the rook on the 7th rank, the minority attack, and the positional sacrifice. These are the weapons of positional mastery.',
    board: null,
    interactive: false,
  },

  // ─── Zugzwang ───────────────────────────────────────────────────────────────
  {
    id: 'zugzwang-intro',
    chapter: 'Advanced Concepts',
    title: 'Zugzwang',
    icon: '😵',
    description: 'Zugzwang is a German word meaning "compulsion to move." It\'s a situation where having to move is actually a disadvantage — any move you make weakens your position. In the endgame, kings and pawns often reach zugzwang: whoever must move loses. Here, it\'s Black\'s turn and Black is in zugzwang. If the black King moves off e7, white\'s King advances. If Black plays ...Kf8, white\'s King reaches e6 and queens first. Black is lost because every move is bad!',
    board: [
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
    ],
    interactive: false,
  },
  {
    id: 'zugzwang-puzzle',
    chapter: 'Advanced Concepts',
    title: 'Reach the Opposition',
    icon: '😵',
    description: 'The opposition is the key to king-and-pawn endgames. Two kings face each other with one square between — whoever must move LOSES the opposition. Here, move your King to e4 to take the opposition directly facing the black King on e6. Now Black is in zugzwang — they must give way, and your King will march forward, support the pawn on e5, and escort it to promotion!',
    board: [
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    movingPiece: 'K',
    expectedMoves: [[5,4,4,4]],
    hint: 'Click your King on e3 and step to e4. You now have the opposition — Black\'s King must move aside (zugzwang!), and you\'ll advance to support your pawn on e5 as it marches to promotion.',
  },

  // ─── Prophylaxis ────────────────────────────────────────────────────────────
  {
    id: 'prophylaxis-intro',
    chapter: 'Advanced Concepts',
    title: 'Prophylaxis',
    icon: '🛡️',
    description: 'Prophylaxis means "preventive medicine" — in chess, it\'s the art of anticipating and stopping your opponent\'s plans before they happen. Before making your own move, ask: "What does my opponent want to do?" Then prevent it! Here, Black is planning to break free with ...c5, challenging White\'s center and freeing the light-squared bishop. White can play prophylactically by placing a piece to control c5, or by playing c5 first to deny the break. A grandmaster doesn\'t just play good moves — they stop the opponent\'s good moves.',
    board: [
      ['r',null,'b','q','k','b','n','r'],
      ['p','p',null,'p','p','p','p','p'],
      [null,'n',null,null,null,'n',null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,'N',null,null],
      ['P','P','P','P',null,'P','P','P'],
      ['R','N','B','Q','K','B',null,'R'],
    ],
    interactive: false,
  },

  // ─── Two Weaknesses ────────────────────────────────────────────────────────
  {
    id: 'two-weaknesses-intro',
    chapter: 'Advanced Concepts',
    title: 'The Principle of Two Weaknesses',
    icon: '⚔️',
    description: 'One weakness can be defended. Two weaknesses on opposite sides of the board cannot — the defender can\'t be everywhere at once. The principle: create a second weakness far from the first, then switch your attack between them. The defender scrambles to cover both and eventually collapses. Here, Black has a weak pawn on a7 (attacked by the rook) and a weak King on g8. White can attack the queenside, then swing to the kingside — Black can\'t defend both fronts.',
    board: [
      [null,null,null,null,null,null,'k','r'],
      ['p',null,null,null,null,'p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['R',null,null,null,'K',null,null,null],
    ],
    interactive: false,
  },
  {
    id: 'two-weaknesses-puzzle',
    chapter: 'Advanced Concepts',
    title: 'Attack the Second Weakness',
    icon: '⚔️',
    description: 'Black\'s King on g8 is well-defended, but the a7 pawn on the far side of the board is weak and undefended. Your rook on a1 already eyes it. March your King toward the center — kings are powerful in the endgame! Move your King to d2, heading toward the queenside to support the rook\'s attack on the a7 pawn. You\'re creating a second front that Black can\'t defend.',
    board: [
      [null,null,null,null,null,null,'k',null],
      ['p',null,null,null,'p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['R',null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    movingPiece: 'K',
    expectedMoves: [[7,4,6,3]],
    hint: 'Click your King on e1 and move it to d2. Active kings are crucial in the endgame — you\'re heading to support the rook\'s attack on the weak a7 pawn, creating a second weakness Black can\'t defend.',
  },

  // ─── Rook on the 7th ───────────────────────────────────────────────────────
  {
    id: 'rook-7th-intro',
    chapter: 'Advanced Concepts',
    title: 'Rook on the 7th Rank',
    icon: '🔥',
    description: 'A rook on the 7th rank (the 2nd rank from the opponent\'s perspective) is one of the most powerful assets in chess. It devours pawns, restricts the enemy King to the back rank, and creates deadly threats. There\'s a saying: "A rook on the 7th is worth a pawn." Here, the white rook has invaded to c7 — it attacks the f7 pawn along the 7th rank, and the black King is trapped on the 8th rank. Black is under severe pressure.',
    board: [
      [null,null,null,null,null,null,'k','r'],
      [null,null,'R',null,null,'p','p',null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,'p',null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P',null,'P','P',null,'P',null,'P'],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: false,
  },
  {
    id: 'rook-7th-puzzle',
    chapter: 'Advanced Concepts',
    title: 'Invade with the Rook',
    icon: '🔥',
    description: 'The 7th rank is open for your rook to invade! Slide your rook to c7 — it lands on the 7th rank, attacking the a7 pawn and trapping the black King on the 8th rank. From c7 the rook dominates: it can sweep across to grab pawns and the black King can never escape the back rank.',
    board: [
      [null,null,null,null,'k',null,null,null],
      ['p',null,null,null,'p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P',null,'P','P','P','P','P'],
      [null,null,'R',null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    movingPiece: 'R',
    expectedMoves: [[7,2,1,2]],
    hint: 'Click your rook on c1 and slide it to c7. You\'ve invaded the 7th rank — the rook now attacks a7 and traps the black King on the back rank. This is a decisive positional advantage!',
  },

  // ─── Minority Attack ────────────────────────────────────────────────────────
  {
    id: 'minority-attack-intro',
    chapter: 'Advanced Concepts',
    title: 'The Minority Attack',
    icon: '🏹',
    description: 'Sometimes fewer pawns can create weaknesses in a larger pawn structure. In the minority attack, you use just two or three pawns to attack an enemy pawn majority of three or four, forcing them to create a backward or doubled pawn. This classic plan arises often in the Queen\'s Pawn structures. Here, White has a queenside minority (a2, b2) attacking Black\'s majority (a6, b6, c6). White will play b4-b5, and after ...cxb5, axb5, Black is left with a backward a6 pawn — a permanent weakness.',
    board: [
      ['r','n','b','q','k',null,null,'r'],
      ['p','p','p',null,'p','p','p','p'],
      [null,null,'p',null,null,'n',null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,'N',null,null],
      ['P','P','P','P',null,'P','P','P'],
      ['R','N','B','Q','K','B',null,'R'],
    ],
    interactive: false,
  },

  // ─── Positional Sacrifice ───────────────────────────────────────────────────
  {
    id: 'positional-sacrifice-intro',
    chapter: 'Advanced Concepts',
    title: 'The Positional Sacrifice',
    icon: '💎',
    description: 'Not all sacrifices are tactical — a positional sacrifice gives up material not for an immediate checkmate, but for long-term compensation: better piece activity, a devastating outpost, or permanent initiative. The material is given up strategically, not for a forced sequence. Here, White sacrifices the e5 pawn — but in return, the knight that captures it is trapped on e5, and White gains a massive lead in development and open lines for all pieces. The compensation outweighs the pawn. Positional sacrifices require vision and courage!',
    board: [
      ['r','n','b','q','k','b',null,'r'],
      ['p','p','p',null,null,'p','p','p'],
      [null,null,null,null,'n',null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,'N',null,null],
      ['P','P','P','P',null,'P','P','P'],
      ['R','N','B','Q','K','B',null,'R'],
    ],
    interactive: false,
  },
];