// Basic piece movement and capture lessons
// board: 8x8 array, null = empty, uppercase = white, lowercase = black
// expectedMoves: array of [fromR, fromC, toR, toC] — any one of these is a valid "correct" move

export const BASICS_LESSONS = [
  // ─── Chapter 1: The Board & Setup ───────────────────────────────────────────
  {
    id: 'board-intro',
    chapter: 'The Board',
    title: 'Welcome to Chess',
    icon: '♟',
    description: 'Chess is played on an 8×8 board of alternating light and dark squares. White always moves first. Your goal is to trap (checkmate) the enemy King.',
    board: null,
    interactive: false,
  },
  {
    id: 'board-setup',
    chapter: 'The Board',
    title: 'Starting Position',
    icon: '♙',
    description: 'This is how the pieces start. White occupies rows 1–2, Black rows 7–8. Notice each side mirrors the other. Take a moment to study the layout.',
    board: [
      ['r','n','b','q','k','b','n','r'],
      ['p','p','p','p','p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P','P','P','P','P','P','P'],
      ['R','N','B','Q','K','B','N','R'],
    ],
    interactive: false,
  },

  // ─── Chapter 2: The Pawns ────────────────────────────────────────────────────
  {
    id: 'pawn-move',
    chapter: 'The Pawn',
    title: 'How Pawns Move',
    icon: '♙',
    description: 'Pawns move forward one square at a time — but on their very first move they can advance two squares. Move the pawn forward to continue.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[6,4,5,4],[6,4,4,4]],
    hint: 'Click the pawn on e2, then click e3 or e4 to move it forward.',
  },
  {
    id: 'pawn-capture',
    chapter: 'The Pawn',
    title: 'How the Pawn Captures',
    icon: '♙',
    description: 'Pawns capture one square diagonally forward — they cannot capture straight ahead. Capture the black pawn!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'p',null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[5,4,4,3]],
    hint: 'Click your pawn on e3, then click the black pawn on d4 to capture it diagonally.',
  },

  // ─── Chapter 3: The Rook ─────────────────────────────────────────────────────
  {
    id: 'rook-move',
    chapter: 'The Rook',
    title: 'How the Rook Moves',
    icon: '♖',
    description: 'The Rook slides any number of squares horizontally or vertically. It cannot jump over other pieces. Move the rook anywhere to continue.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'R',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'R',
    hint: 'Click the Rook, then click any square in the same row or column.',
  },
  {
    id: 'rook-capture',
    chapter: 'The Rook',
    title: 'How the Rook Captures',
    icon: '♖',
    description: 'The Rook captures by moving to an enemy piece\'s square along its line of attack — horizontally or vertically. It cannot jump. Capture the black pawn!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'p',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'R',null,null,null,'K'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,3,5,3]],
    movingPiece: 'R',
    hint: 'Click your Rook on d1, then click the black pawn on d6 to capture it along the file.',
  },

  // ─── Chapter 4: The Bishop ───────────────────────────────────────────────────
  {
    id: 'bishop-move',
    chapter: 'The Bishop',
    title: 'How the Bishop Moves',
    icon: '♗',
    description: 'The Bishop slides any number of squares diagonally. Each bishop stays on its own color for the entire game. Move the bishop to continue.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'B',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'B',
    hint: 'Click the Bishop, then click any square diagonally from it.',
  },
  {
    id: 'bishop-capture',
    chapter: 'The Bishop',
    title: 'How the Bishop Captures',
    icon: '♗',
    description: 'The Bishop captures by sliding diagonally onto an enemy piece\'s square. It stays on its own color forever. Capture the black pawn!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['p',null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,'B',null,'K'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,5,2,0]],
    movingPiece: 'B',
    hint: 'Click your Bishop on f1, then click the black pawn on a6. The Bishop slides along its long diagonal to capture it.',
  },

  // ─── Chapter 5: The Knight ───────────────────────────────────────────────────
  {
    id: 'knight-move',
    chapter: 'The Knight',
    title: 'How the Knight Moves',
    icon: '♘',
    description: 'The Knight moves in an "L" shape: two squares in one direction, then one square perpendicular. It\'s the only piece that can jump over others!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'N',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'N',
    hint: 'Click the Knight, then click one of the highlighted L-shaped squares.',
  },
  {
    id: 'knight-capture',
    chapter: 'The Knight',
    title: 'How the Knight Captures',
    icon: '♘',
    description: 'The Knight captures by landing on an enemy piece\'s square with its L-shaped jump. Unlike other pieces, it can leap over anything to get there! Capture the black pawn!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,'p',null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'N',null,null,'K'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,4,5,5]],
    movingPiece: 'N',
    hint: 'Click your Knight on e1, then click the black pawn on f3. The Knight jumps in an L-shape to capture it.',
  },

  // ─── Chapter 6: The Queen ────────────────────────────────────────────────────
  {
    id: 'queen-move',
    chapter: 'The Queen',
    title: 'How the Queen Moves',
    icon: '♕',
    description: 'The Queen is the most powerful piece — she can move any number of squares in any direction (horizontal, vertical, or diagonal). Use her wisely!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'Q',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'Q',
    hint: 'Click the Queen, then click any square she can reach.',
  },
  {
    id: 'queen-capture',
    chapter: 'The Queen',
    title: 'How the Queen Captures',
    icon: '♕',
    description: 'The Queen captures by moving onto an enemy piece\'s square — in any direction (horizontal, vertical, or diagonal). She is devastating on open lines! Capture the black pawn!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,'p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'Q',null,null,'K'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,4,4,7]],
    movingPiece: 'Q',
    hint: 'Click your Queen on e1, then click the black pawn on h4 to capture it diagonally.',
  },

  // ─── Chapter 7: The King ─────────────────────────────────────────────────────
  {
    id: 'king-move',
    chapter: 'The King',
    title: 'How the King Moves',
    icon: '♔',
    description: 'The King can move one square in any direction. Protect your King at all costs — if he is trapped with no escape (checkmate), you lose!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: null,
    movingPiece: 'K',
    hint: 'Click the King, then click any adjacent square to move him.',
  },
  {
    id: 'king-capture',
    chapter: 'The King',
    title: 'How the King Captures',
    icon: '♔',
    description: 'The King captures by stepping one square onto an enemy piece\'s square in any direction. But be careful — never capture a piece that is defended, or your King will be in danger! Capture the black pawn!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'p',null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,4,6,4]],
    movingPiece: 'K',
    hint: 'Click your King on e1, then click the black pawn on e2 to capture it. The King steps forward one square.',
  },
];