// Endgame concept lessons: check, checkmate, stalemate, draws

export const ENDGAME_LESSONS = [
  {
    id: 'check',
    chapter: 'Finishers',
    title: 'Putting the King in Check',
    icon: '⚔️',
    description: 'When your piece directly threatens the enemy King, that\'s "Check!" The opponent must immediately deal with the threat — by moving the King, blocking the check, or capturing the attacking piece. Move the Queen to d8 to give check from a safe distance — the King can\'t capture the Queen because they\'re not adjacent!',
    board: [
      ['k',null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'Q',null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[6,3,0,3]],
    hint: 'Move the Queen up the d-file to d8. From d8 she attacks along the 8th rank directly at the King on a8 — that\'s check! The King can\'t capture the Queen because they\'re three squares apart.',
  },
  {
    id: 'checkmate',
    chapter: 'Finishers',
    title: 'Checkmate in One!',
    icon: '♛',
    description: 'Checkmate ends the game immediately. The black King is trapped in the corner — his own pawns block his escape. Slide the Queen to c8 to deliver checkmate!',
    board: [
      ['k',null,null,null,null,null,null,null],
      ['p','p',null,null,null,null,null,null],
      [null,null,'Q',null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[2,2,0,2]],
    hint: 'Move the Queen from c6 up to c8. The King on a8 is in check, b8 is covered by the Queen, and the pawns on a7 and b7 block any escape — checkmate!',
  },
  {
    id: 'stalemate',
    chapter: 'Finishers',
    title: 'Stalemate',
    icon: '🤝',
    description: 'Stalemate is a draw that happens when the player whose turn it is has NO legal moves — but their King is NOT in check. It\'s not checkmate because the King isn\'t attacked. In this position, it\'s Black\'s turn. The Black King on h8 has no safe squares: g8 and g7 are covered by the white Queen, and h7 is covered diagonally. Since the King isn\'t in check, this is stalemate — a draw, not a win!',
    board: [
      [null,null,null,null,null,null,null,'k'],
      [null,null,null,null,null,'K',null,null],
      [null,null,null,null,null,null,'Q',null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
    ],
    interactive: false,
  },
  {
    id: 'threefold-repetition',
    chapter: 'Finishers',
    title: 'Threefold Repetition',
    icon: '🔁',
    description: 'If the exact same position occurs three times in a game (with the same player to move and the same castling/en passant rights), either player can claim a draw. This prevents endless shuffling of pieces back and forth. It\'s a safety valve — if nobody is making progress, the game ends in a draw. You\'ll see this often when players repeat moves to avoid risk or secure a result.',
    board: null,
    interactive: false,
  },
  {
    id: 'insufficient-material',
    chapter: 'Finishers',
    title: 'Insufficient Material',
    icon: '⚖️',
    description: 'A draw is automatic when neither side has enough pieces to deliver checkmate. King vs King can never produce checkmate — neither King can attack the other. King + Bishop vs King and King + Knight vs King are also draws, since a single minor piece can\'t force checkmate. In this position, only the two Kings remain — the game is a draw by insufficient material.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: false,
  },
];