// Opening principles lessons

export const OPENING_LESSONS = [
  {
    id: 'control-center',
    chapter: 'Opening Principles',
    title: 'Control the Center',
    icon: '🎯',
    description: 'The center squares (d4, e4, d5, e5) are the most important real estate on the board. Pieces in the center control more squares and can swing to either flank. Your first move should fight for the center — move a center pawn two squares forward to stake your claim!',
    board: [
      ['r','n','b','q','k','b','n','r'],
      ['p','p','p','p','p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P','P','P','P','P','P','P'],
      ['R','N','B','Q','K','B','N','R'],
    ],
    interactive: true,
    playerColor: 'white',
    movingPiece: 'P',
    expectedMoves: [[6,4,4,4],[6,3,4,3]],
    hint: 'Click your e-pawn (e2) and move it to e4, or your d-pawn (d2) to d4. Either move seizes the center!',
  },
  {
    id: 'develop-pieces',
    chapter: 'Opening Principles',
    title: 'Develop Your Pieces',
    icon: '🌱',
    description: 'After fighting for the center, get your minor pieces (knights and bishops) into the game. A piece sitting on its home square does nothing! Develop a knight to an active square — knights are most powerful when placed toward the center.',
    board: [
      ['r','n','b','q','k','b','n','r'],
      ['p','p','p','p','p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P','P','P',null,'P','P','P'],
      ['R','N','B','Q','K','B','N','R'],
    ],
    interactive: true,
    playerColor: 'white',
    movingPiece: 'N',
    expectedMoves: [[7,6,5,5],[7,1,5,2]],
    hint: 'Click your knight on g1 and move it to f3 (Nf3), or the knight on b1 to c3 (Nc3). Both are excellent developing moves that control the center.',
  },
  {
    id: 'knights-before-bishops',
    chapter: 'Opening Principles',
    title: 'Knights Before Bishops',
    icon: '♞',
    description: 'A common guideline: develop knights before bishops. Knights are less flexible — they have fewer good squares and take longer to reposition. Bishops have long diagonal options and can be developed later without losing tempo. In this position, both sides have followed this principle: all four knights are out, but the bishops are still home. This is a model opening development.',
    board: [
      ['r',null,'b','q','k','b',null,'r'],
      ['p','p','p','p',null,'p','p','p'],
      [null,'n',null,null,null,null,'n',null],
      [null,null,null,null,'p',null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,'N',null,null,null,'N',null,null],
      ['P','P','P','P',null,'P','P','P'],
      ['R',null,'B','Q','K','B',null,'R'],
    ],
    interactive: false,
  },
  {
    id: 'dont-move-twice',
    chapter: 'Opening Principles',
    title: 'Don\'t Move the Same Piece Twice',
    icon: '⏱️',
    description: 'In the opening, every move is precious — this concept is called "tempo." Each turn you should bring a NEW piece into the game. Here, White wasted three turns shuffling the knight (Nf3–Ng5–Nf3) trying to attack f7, but the attack failed and the knight ended up right back where it started. Meanwhile, Black used those same three turns to develop three different pieces: a pawn to d5, a knight to c6, and a bishop to g4. Black has a huge lead in development. Don\'t squander your opening moves!',
    board: [
      ['r',null,'b','q','k','b','n','r'],
      ['p','p','p',null,null,'p','p','p'],
      [null,'n',null,null,null,null,null,null],
      [null,null,null,null,'p',null,null,null],
      [null,null,null,'p','P',null,'b',null],
      [null,null,null,null,null,'N',null,null],
      ['P','P','P','P',null,'P','P','P'],
      ['R',null,'B','Q','K','B',null,'R'],
    ],
    interactive: false,
  },
  {
    id: 'castle-early',
    chapter: 'Opening Principles',
    title: 'King Safety: Castle Early',
    icon: '🛡️',
    description: 'An exposed King in the center is a target. Once you\'ve developed a piece or two and cleared the path, castle to tuck your King away safely behind a wall of pawns. This also brings your Rook into the game. Here you\'ve played e4 and Nf3 — the kingside is clear. Castle kingside to safety!',
    board: [
      [null,null,null,null,'k',null,null,'r'],
      ['p','p','p','p','p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,'N',null,null],
      ['P','P','P','P',null,'P','P','P'],
      ['R',null,null,null,'K',null,null,'R'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,4,7,6]],
    hint: 'Click your King on e1, then click g1. The King slides to safety behind the pawns, and the Rook jumps to f1 — now both pieces are active and the King is protected!',
  },
  {
    id: 'queen-out-too-early',
    chapter: 'Opening Principles',
    title: 'Don\'t Bring the Queen Out Too Early',
    icon: '⚠️',
    description: 'The Queen is your most powerful piece — but that makes her a target. If you bring her out before your other pieces are developed, your opponent can attack her with weaker pieces and gain free tempo. Here, White rushed the Queen to e4. Black simply plays ...Nc5, attacking the Queen and developing at the same time. White must waste a move retreating the Queen, while Black keeps developing. The lesson: develop your minor pieces first, and bring the Queen out only when she\'s safe.',
    board: [
      [null,null,null,null,'k',null,null,null],
      ['p','p','p','p','p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,'n',null,null,null,null,null],
      [null,null,null,null,'Q',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: false,
  },
  {
    id: 'fools-mate',
    chapter: 'Opening Principles',
    title: 'The Fool\'s Mate',
    icon: '💀',
    description: 'This is the fastest possible checkmate — just two moves! White blundered by moving the f-pawn and g-pawn, exposing the King\'s diagonal to the Black Queen. Black plays Qh4# — the Queen attacks the King along the h4–e1 diagonal, and nothing can block or escape. The lesson: never weaken the squares around your King in the opening. The f- and g-pawns are your King\'s shield — moving them early creates fatal weaknesses. Don\'t be the Fool!',
    board: [
      ['r','n','b',null,'k','b','n','r'],
      ['p','p','p','p',null,'p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'p',null,null,null],
      [null,null,null,null,null,null,'P','q'],
      [null,null,null,null,null,'P',null,null],
      ['P','P','P','P','P',null,null,'P'],
      ['R','N','B','Q','K','B','N','R'],
    ],
    interactive: false,
  },
];