// Special moves lessons: castling, en passant, pawn promotion

export const SPECIAL_MOVES_LESSONS = [
  {
    id: 'castling-kingside',
    chapter: 'Special Moves',
    title: 'Castling: Kingside',
    icon: '🏰',
    description: 'Castling is a special move that protects your King and activates your Rook in one move. Move the King two squares toward the Rook — the Rook jumps over to the other side. You can only castle if neither piece has moved, the path is clear, and the King isn\'t passing through an attacked square. Castle kingside!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,'R'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,4,7,6]],
    hint: 'Click your King on e1, then click g1. The King moves two squares right, and the Rook jumps over to f1.',
  },
  {
    id: 'castling-queenside',
    chapter: 'Special Moves',
    title: 'Castling: Queenside',
    icon: '🏰',
    description: 'Queenside castling works the same way — the King moves two squares toward the Rook on the left, and the Rook jumps over. Note that the b1 square must also be empty, even though the King doesn\'t pass through it. Castle queenside!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['R',null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,4,7,2]],
    hint: 'Click your King on e1, then click c1. The King moves two squares left, and the Rook jumps over to d1.',
  },
  {
    id: 'en-passant',
    chapter: 'Special Moves',
    title: 'En Passant',
    icon: '👻',
    description: 'En passant ("in passing") is a special pawn capture. When an enemy pawn moves two squares forward and lands beside yours, you may capture it as if it only moved one square — but only on your very next move! The black pawn just advanced two squares. Capture it en passant!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'p','P',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    enPassantTarget: [2, 3],
    expectedMoves: [[3,4,2,3]],
    hint: 'Click your pawn on e5, then click d6 (the empty square behind the black pawn). Your pawn captures diagonally to d6 — the black pawn on d5 is removed even though you moved to an empty square!',
  },
  {
    id: 'pawn-promotion',
    chapter: 'Special Moves',
    title: 'Pawn Promotion',
    icon: '👑',
    description: 'When a pawn reaches the far end of the board, it must promote — it transforms into a Queen, Rook, Bishop, or Knight of your choice. Almost always, you\'ll pick the Queen since she\'s the most powerful piece. Push your pawn to the last rank to promote it!',
    board: [
      [null,null,null,null,'k',null,null,null],
      ['P',null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[1,0,0,0]],
    hint: 'Click your pawn on a7, then click a8. The pawn promotes to a Queen — a powerful new piece joins the battle!',
  },
];