// Intermediate strategy lessons: outposts, weak squares, pawn structures,
// good/bad bishops, open files, piece coordination, overextended pieces.

export const STRATEGY_LESSONS = [
  {
    id: 'strategy-intro',
    chapter: 'Intermediate Strategy',
    title: 'Strategy vs Tactics',
    icon: '🗺️',
    description: 'Tactics win material in the short term. Strategy is the long-term plan — improving your pieces, creating weaknesses in the enemy camp, and maneuvering toward winning positions. In this chapter you\'ll learn the building blocks of positional chess: outposts, weak squares, pawn structures, good and bad bishops, open files, and piece coordination. Master these ideas and you\'ll know what to do when there are no immediate tactics.',
    board: null,
    interactive: false,
  },

  // ─── Outposts ──────────────────────────────────────────────────────────────
  {
    id: 'outpost-intro',
    chapter: 'Intermediate Strategy',
    title: 'The Outpost',
    icon: '🏰',
    description: 'An outpost is a square on the 4th–6th rank, supported by your own pawn, that cannot be driven away by an enemy pawn. A knight on an outpost is a monster — it controls key squares deep in enemy territory. Here, the white knight on d5 is a perfect outpost: it\'s supported by the pawn on c4, and no black pawn can attack it. The knight dominates the position, eyeing c7, e7, b6, f6, and b4.',
    board: [
      ['r','n','b','q','k','b','n','r'],
      ['p','p',null,null,null,'p','p','p'],
      [null,null,null,'p',null,'n',null,null],
      [null,null,null,'N',null,null,null,null],
      [null,null,'P',null,null,null,null,null],
      [null,null,null,null,null,'N',null,null],
      ['P','P',null,'P','P','P','P','P'],
      ['R',null,'B','Q','K','B',null,'R'],
    ],
    interactive: false,
  },
  {
    id: 'outpost-puzzle',
    chapter: 'Intermediate Strategy',
    title: 'Place the Knight on the Outpost',
    icon: '♞',
    description: 'The d5 square is a powerful outpost — supported by your pawn on c4. Black\'s pawns on c6 and e6 can capture into d5, but after any exchange your c4 pawn recaptures, keeping a strong white piece firmly planted on d5. Jump your knight to d5 and dominate the enemy camp. From there it controls c7, e7, b6, f6, and b4 — a truly dominant piece!',
    board: [
      ['r','n','b','q','k','b',null,'r'],
      ['p','p',null,null,null,'p','p','p'],
      [null,null,'p',null,'p','n',null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,'P',null,null,null,null,null],
      [null,null,'N',null,null,null,null,null],
      ['P','P',null,'P','P','P','P','P'],
      ['R',null,'B','Q','K','B',null,'R'],
    ],
    interactive: true,
    playerColor: 'white',
    movingPiece: 'N',
    expectedMoves: [[5,2,3,3]],
    hint: 'Click your knight on c3 and jump it to d5. The square is protected by your c4 pawn and can\'t be attacked by any black pawn — a textbook outpost!',
  },

  // ─── Weak Squares ──────────────────────────────────────────────────────────
  {
    id: 'weak-square-intro',
    chapter: 'Intermediate Strategy',
    title: 'Weak Squares',
    icon: '🔲',
    description: 'A weak square is one that can never be protected by a pawn. Once a pawn moves or is traded, the squares it used to guard become permanent weaknesses. Here, Black\'s f6 square is weak — the e7 and g7 pawns have advanced, and no black pawn can ever guard f6 again. White can plant a piece there and it will be a permanent thorn in Black\'s position.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,'p','p',null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,'N',null,null],
      ['P','P','P','P','P','P','P','P'],
      ['R',null,'B','Q','K',null,null,'R'],
    ],
    interactive: false,
  },

  // ─── Pawn Structures ───────────────────────────────────────────────────────
  {
    id: 'pawn-structure-intro',
    chapter: 'Intermediate Strategy',
    title: 'Pawn Structures',
    icon: '🧱',
    description: 'Pawns are the skeleton of your position — they determine the terrain. Unlike pieces, pawns can\'t move backward, so every pawn move creates permanent strengths and weaknesses. The most common structures are: the pawn chain (diagonal line of pawns protecting each other), the pawn island (isolated group), the doubled pawns (two pawns on the same file), and the backward pawn (a pawn that can\'t be supported by neighbors). Here, White has a healthy pawn chain (d4-e3-f2), while Black suffers from doubled pawns on the c-file and an isolated d-pawn.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,'p','p',null,null,null,null],
      [null,null,'p',null,'p','p','p','p'],
      [null,null,null,'p',null,null,null,null],
      [null,null,null,'P',null,null,null,null],
      [null,null,'P',null,'P',null,null,null],
      ['P','P',null,null,null,'P','P','P'],
      ['R',null,'B','Q','K','B',null,'R'],
    ],
    interactive: false,
  },
  {
    id: 'pawn-chain-puzzle',
    chapter: 'Intermediate Strategy',
    title: 'Attack the Base of the Chain',
    icon: '🔗',
    description: 'A pawn chain is strongest at its tip and weakest at its base — the rearmost pawn. If you capture the base, the whole chain can crumble. Here, Black has a pawn chain on d5-c6-b7. The base is b7. Attack it by pushing your a-pawn to a4-a5, preparing to undermine the chain. Push your a-pawn forward to challenge the base!',
    board: [
      ['r',null,'b','q','k','b','n','r'],
      ['p','p','p',null,null,'p','p','p'],
      [null,'n',null,'p',null,'n',null,null],
      [null,null,null,null,'p',null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,'N',null,null],
      ['P','P','P','P',null,'P','P','P'],
      ['R','N','B','Q','K','B',null,'R'],
    ],
    interactive: true,
    playerColor: 'white',
    movingPiece: 'P',
    expectedMoves: [[6,0,4,0]],
    hint: 'Click your a-pawn on a2 and push it to a4. You\'re preparing a4-a5 to attack the base of Black\'s pawn chain on b7 — undermine the chain and it falls!',
  },

  // ─── Good and Bad Bishops ──────────────────────────────────────────────────
  {
    id: 'good-bad-bishop-intro',
    chapter: 'Intermediate Strategy',
    title: 'Good and Bad Bishops',
    icon: '♝',
    description: 'A bishop is only as good as its pawn structure allows. A "good bishop" has its diagonals open — its own pawns are on the OPPOSITE color. A "bad bishop" is trapped behind its own pawns, blocked on the same color squares. Here, White\'s dark-squared bishop on c1 is bad — it\'s completely blocked by the pawns on b2 and d2, with nowhere to go. Meanwhile, White\'s light-squared bishop on f1 is good — its pawns are on dark squares, leaving the light diagonals wide open. On the Black side, the bishop on g7 is an excellent fianchettoed bishop — it sweeps the long a1–h8 diagonal with no obstructions from its own pawns. Always keep your bishops\' diagonals open!',
    board: [
      ['r','n','b','q','k',null,null,'r'],
      ['p','p',null,'p','p',null,'b','p'],
      [null,null,'p',null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P',null,'P',null,'P','P','P'],
      ['R','N','B','Q','K','B','N','R'],
    ],
    interactive: false,
  },

  // ─── Open Files ────────────────────────────────────────────────────────────
  {
    id: 'open-file-intro',
    chapter: 'Intermediate Strategy',
    title: 'Open Files and the Rook',
    icon: '🛣️',
    description: 'Rooks are long-range pieces that thrive on open files — columns with no pawns. Controlling an open file lets you invade the enemy position, often reaching the 7th rank where rooks devour pawns and threaten the King. Here, White has queenside castled — the King is safe on c1 and the rook has swung to d1. Both c-pawns have been traded off, leaving the c-file completely open. The rook on d1 is poised to slide to c1 and seize the open file. The player who controls the open file can "double rooks" (stack two rooks on the same file) for overwhelming pressure.',
    board: [
      ['r','n','b','q','k','b',null,'r'],
      ['p','p',null,'p','p','p','p','p'],
      [null,null,null,null,null,'n','B',null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,'P',null,'N',null,null],
      ['P','P',null,'N','Q','P','P','P'],
      [null,null,'K','R',null,'B',null,'R'],
    ],
    interactive: false,
  },
  {
    id: 'open-file-puzzle',
    chapter: 'Intermediate Strategy',
    title: 'Seize the Open File',
    icon: '🛣️',
    description: 'The c-file is completely open — no pawns on it at all. Slide your rook to c1 to seize control of this critical file. From c1 your rook controls the entire c-file and can eventually penetrate to c7 or c8, attacking Black\'s position from behind.',
    board: [
      ['r','n','b','q','k','b','n','r'],
      ['p','p','p',null,'p','p','p','p'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P',null,'P','P','P','P','P'],
      ['R',null,null,null,'K',null,null,'R'],
    ],
    interactive: true,
    playerColor: 'white',
    movingPiece: 'R',
    expectedMoves: [[7,0,7,2]],
    hint: 'Click your rook on a1 and slide it to c1. You now control the open c-file — this gives you a long-term positional advantage and invasion routes into Black\'s camp.',
  },

  // ─── Piece Coordination ────────────────────────────────────────────────────
  {
    id: 'coordination-intro',
    chapter: 'Intermediate Strategy',
    title: 'Piece Coordination',
    icon: '🤝',
    description: 'Pieces working together are far stronger than the same pieces acting alone. Coordination means your pieces support each other, attack the same targets, and defend key squares as a unit. Here, White has excellent coordination: the bishop on b2 eyes the long diagonal, the rook on e1 supports the center, and the knight on f3 can jump to e5 or d4 — every piece supports the plan of attacking Black\'s position. Black\'s pieces, by contrast, are passive and disconnected.',
    board: [
      [null,null,null,null,'k',null,null,'r'],
      ['p','p','p',null,null,'p','p','p'],
      [null,'n',null,'p','p','n',null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'P',null,null,null],
      [null,null,null,null,null,'N',null,null],
      ['P','B','P','P',null,'P','P','P'],
      [null,null,null,null,'R','K',null,null],
    ],
    interactive: false,
  },

  // ─── Overextended Pieces ───────────────────────────────────────────────────
  {
    id: 'overextension-intro',
    chapter: 'Intermediate Strategy',
    title: 'Don\'t Overextend',
    icon: '📉',
    description: 'Pushing too many pawns forward without support creates targets. An overextended position looks aggressive but is actually fragile — each advanced pawn is a weakness the opponent can attack. Here, White greedily pushed pawns to g5 and h5, hoping to storm Black\'s King. But these pawns are undefended and weak. Black can undermine them with ...f6, hitting the g5 pawn, or ...h6, challenging g5. When you advance, always have support behind your pawns!',
    board: [
      ['r','n','b','q','k','b','n','r'],
      ['p','p','p','p','p',null,null,'p'],
      [null,null,null,null,null,null,'p','p'],
      [null,null,null,null,null,'P','P',null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P','P','P','P',null,null,'P'],
      ['R','N','B','Q','K','B','N','R'],
    ],
    interactive: false,
  },
];