// Chess tactics lessons: fork, pin, skewer, discovered attack, deflection
// All board positions and move coordinates have been verified.

export const TACTICS_LESSONS = [
  {
    id: 'tactics-intro',
    chapter: 'Chess Tactics',
    title: 'What Are Tactics?',
    icon: '🧠',
    description: 'Tactics are short sequences of moves that win material or deliver checkmate. They are the heart of practical chess — most games below master level are decided by tactics. In this chapter you\'ll learn the five most important tactical patterns: the fork, the pin, the skewer, the discovered attack, and the deflection. Recognizing these patterns will transform your results. Let\'s begin!',
    board: null,
    interactive: false,
  },

  // ─── The Fork ──────────────────────────────────────────────────────────────
  {
    id: 'fork-intro',
    chapter: 'Chess Tactics',
    title: 'The Fork',
    icon: '🍴',
    description: 'A fork is when one piece attacks two or more enemy pieces at the same time. The opponent can only save one piece, so you win the other. Knights are especially dangerous forkers because they can jump over blockers. Here, a white knight has landed on f7 — it forks the black King on h8 and the black Queen on d8 simultaneously. Black must deal with the check, and the Queen falls!',
    board: [
      [null,null,null,'q',null,null,null,'k'],
      [null,null,null,null,null,'N',null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P','P','P','P','P','P','P'],
      ['R','N','B','Q','K','B',null,'R'],
    ],
    interactive: false,
  },
  {
    id: 'fork-puzzle-knight',
    chapter: 'Chess Tactics',
    title: 'Knight Fork: Win the Queen',
    icon: '♞',
    description: 'The black King on h8 and the black Queen on d8 are both on the back rank, separated by three files. A knight on f7 attacks both squares at once! Jump your knight to f7 to deliver a royal fork — check on the King and an attack on the Queen. Black must respond to the check, and you capture the Queen next move.',
    board: [
      [null,null,null,'q',null,null,null,'k'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'N',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P','P','P','P','P','P','P'],
      ['R',null,null,'Q','K',null,null,'R'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[3,4,1,5]],
    hint: 'Click your knight on e5, then click f7. The knight now attacks the King on h8 (check!) and the Queen on d8 simultaneously — a devastating royal fork!',
  },
  {
    id: 'fork-puzzle-pawn',
    chapter: 'Chess Tactics',
    title: 'Pawn Fork: Two Pieces at Once',
    icon: '♙',
    description: 'Pawns can fork too! Here, a black knight on a6 and a black bishop on c6 sit one file apart on the same rank. Push your pawn to b5 — it attacks both pieces diagonally. Your pawn on a4 supports b5, so even if the bishop captures the forking pawn, you recapture and win the bishop. Black can only save one piece!',
    board: [
      ['r',null,null,null,'k',null,null,'r'],
      ['p','p','p','p','p','p','p','p'],
      ['n',null,'b',null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['P','P',null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,'P','P','P','P','P','P'],
      ['R','N','B','Q','K',null,null,'R'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[4,1,3,1]],
    hint: 'Click your pawn on b4 and push it to b5. The pawn now attacks both the knight on a6 and the bishop on c6 — and your a4 pawn defends b5, so Black can\'t capture the forking pawn. Black can only save one piece!',
  },

  // ─── The Pin ───────────────────────────────────────────────────────────────
  {
    id: 'pin-intro',
    chapter: 'Chess Tactics',
    title: 'The Pin',
    icon: '📌',
    description: 'A pin locks an enemy piece in place because moving it would expose a more valuable piece behind it. In an absolute pin, the piece behind is the King — it\'s illegal to move the pinned piece. Here, the white rook on e1 pins the black bishop on e6 to the black King on e8. The bishop is stuck — it cannot legally move off the e-file.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'b',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'R',null,null,'K'],
    ],
    interactive: false,
  },
  {
    id: 'pin-puzzle-bishop',
    chapter: 'Chess Tactics',
    title: 'Pin the Queen with Your Bishop',
    icon: '📌',
    description: 'The black King on a8 and the black Queen on d5 are on the same diagonal (a8–e4). Slide your bishop to e4 — it pins the Queen to the King. Your pawn on d3 defends the bishop, so if the Queen captures it, you recapture and win the Queen. She can\'t move off the diagonal (that exposes the King), and she can\'t capture the bishop (your d3 pawn recaptures). She\'s completely trapped!',
    board: [
      ['k',null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'q',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'P',null,null,null,null],
      [null,null,null,null,null,null,'B',null],
      [null,null,null,null,null,null,null,'K'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[6,6,4,4]],
    hint: 'Click your bishop on g2 and slide it to e4. The bishop pins the Queen on d5 to the King on a8 along the diagonal — and your d3 pawn defends the bishop, so the Queen can\'t capture it without being recaptured. She\'s trapped!',
  },
  {
    id: 'pin-puzzle-rook',
    chapter: 'Chess Tactics',
    title: 'Absolute Pin with the Rook',
    icon: '📌',
    description: 'The black King on d8 and the black knight on d7 are on the same file. Slide your rook to d1 to pin the knight to the King along the d-file. The knight is absolutely pinned — it cannot legally move because doing so would expose the King to check. Black is stuck and will eventually lose the knight.',
    board: [
      [null,null,null,'k',null,null,null,null],
      [null,null,null,'n',null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['R',null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[7,0,7,3]],
    hint: 'Click your rook on a1, then click d1. The rook now pins the knight on d7 to the King on d8 — the knight is absolutely pinned and cannot escape!',
  },

  // ─── The Skewer ────────────────────────────────────────────────────────────
  {
    id: 'skewer-intro',
    chapter: 'Chess Tactics',
    title: 'The Skewer',
    icon: '🍢',
    description: 'A skewer is the mirror image of a pin. In a pin, the weaker piece is in front. In a skewer, the stronger piece is in front — when it moves out of the way, the piece behind is captured. Think of it like a shish kebab: the King is forced off the skewer, and the piece behind gets taken! Here, the black King on d8 is in front of the black Queen on h8 on the same rank. A rook checks the King, the King steps aside, and the Queen is captured.',
    board: [
      [null,null,null,'k',null,null,null,'q'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['R',null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: false,
  },
  {
    id: 'skewer-puzzle',
    chapter: 'Chess Tactics',
    title: 'Skewer: King and Queen',
    icon: '🍢',
    description: 'The black King on d8 and the black Queen on h8 are lined up on the back rank. Slide your rook to a8 to deliver check along the rank. The King must step off, and then you capture the exposed Queen on h8!',
    board: [
      [null,null,null,'k',null,null,null,'q'],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['R',null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'K',null,null,null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[5,0,0,0]],
    hint: 'Click your rook on a3 and slide it to a8 — check! The King must step off the 8th rank, exposing the Queen on h8 to capture.',
  },

  // ─── Discovered Attack ─────────────────────────────────────────────────────
  {
    id: 'discovered-attack-intro',
    chapter: 'Chess Tactics',
    title: 'The Discovered Attack',
    icon: '💥',
    description: 'A discovered attack happens when you move one piece, revealing an attack from another piece behind it. If the hidden piece attacks the King, it\'s a "discovered check" — the moving piece can do anything it wants, because the opponent must respond to the check first! Here, the white rook on e1 is hidden behind the white knight on e4. If the knight moves, the rook attacks the black King on e8 — discovered check!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'N',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'R',null,null,'K'],
    ],
    interactive: false,
  },
  {
    id: 'discovered-attack-puzzle',
    chapter: 'Chess Tactics',
    title: 'Discovered Check: Win the Queen',
    icon: '💥',
    description: 'Your rook on e1 is aimed at the black King on e8, but your own knight on e4 blocks the e-file. The black Queen sits on a4. Jump the knight to c5 — this reveals a discovered check from the rook, AND the knight on c5 attacks the Queen at the same time! Black must respond to the check, and you capture the Queen.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      ['q',null,null,null,'N',null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,'R',null,null,'K'],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[4,4,3,2]],
    hint: 'Click your knight on e4 and jump it to c5. The rook now gives discovered check to the King on e8, and the knight on c5 attacks the Queen on a4 — Black can\'t defend both!',
  },

  // ─── Deflection ────────────────────────────────────────────────────────────
  {
    id: 'deflection-intro',
    chapter: 'Chess Tactics',
    title: 'The Deflection',
    icon: '🏹',
    description: 'A deflection forces a key defending piece away from its duty — like pulling a shield away from a soldier. Often the piece is guarding another piece or a critical square. By attacking it, you force it to move, and whatever it was defending becomes vulnerable. Here, the black knight on f6 is the sole defender of the black Queen on d7. Your rook on d1 attacks the Queen, but the knight holds it together. Deflect the knight, and the Queen falls!',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,'q',null,null,null,null],
      [null,null,null,null,null,'n',null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'R',null,null,'K',null],
    ],
    interactive: false,
  },
  {
    id: 'deflection-puzzle',
    chapter: 'Chess Tactics',
    title: 'Deflect the Defender',
    icon: '🏹',
    description: 'The black knight on f6 is defending the black Queen on d7 — your rook on d1 attacks the Queen, but the knight keeps it safe. Move your bishop to h4 to attack the knight! If Black saves the knight, the Queen is undefended. If Black saves the Queen, the knight falls. Either way, you win material by removing the defender.',
    board: [
      [null,null,null,null,'k',null,null,null],
      [null,null,null,'q',null,null,null,null],
      [null,null,null,null,null,'n',null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,'B',null],
      [null,null,null,null,null,null,null,null],
      [null,null,null,'R',null,null,'K',null],
    ],
    interactive: true,
    playerColor: 'white',
    expectedMoves: [[5,6,4,7]],
    hint: 'Click your bishop on g3 and slide it to h4. The bishop now attacks the knight on f6 — if the knight moves, the Queen on d7 is undefended. Black can\'t save both pieces!',
  },
];